### ISSUE TITLE
Installed on Ubuntu but not working

### ISSUE THREAD

**Issue by doanva84** [wuba/Picasso#3]
* Installation
```
$ npm install -g @wubafe/picasso
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
$HOME/bin/picasso -> $HOME/lib/node_modules/@wubafe/picasso/bin/index.js

> images@3.2.3 install $HOME/lib/node_modules/@wubafe/picasso/node_modules/images
> node scripts/nothing.js


> node-sass@4.14.1 install $HOME/lib/node_modules/@wubafe/picasso/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.14.1/linux-x64-64_binding.node
...
gyp info ok
Installed to $HOME/lib/node_modules/@wubafe/picasso/node_modules/node-sass/vendor/linux-x64-64/binding.node
+ @wubafe/picasso@0.0.10
added 221 packages from 182 contributors in 1478.519s
```

* Try it
```
$ picasso -s ../mysample.sketch
sketch源文件路径 $HOME/mysample.sketch
解析生成代码存放目录 $HOME
/bin/sh: 1: /Applications/Sketch.app/Contents/Resources/sketchtool/bin/sketchtool: not found
(node:15122) UnhandledPromiseRejectionWarning: Error: Command failed: /Applications/Sketch.app/Contents/Resources/sketchtool/bin/sketchtool -v
/bin/sh: 1: /Applications/Sketch.app/Contents/Resources/sketchtool/bin/sketchtool: not found

    at checkExecSyncError (child_process.js:629:11)
    at Object.execSync (child_process.js:666:13)
    at module.exports ($HOME/lib/node_modules/@wubafe/picasso/src/index.js:158:41)
    at $HOME/lib/node_modules/@wubafe/picasso/bin/index.js:44:11
    at Object.<anonymous> ($HOME/lib/node_modules/@wubafe/picasso/bin/index.js:45:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
(node:15122) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:15122) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by huangwencun** [comment]
Sorry, our sketch parsing tool is based on the sketch software, and the sketch software only has the Mac version, so ubuntu is not supported;
The Premise：
Mac >= 10.15.1
Sketch >= 60
Node >= 8.9.3
